/**
 * Generated by @openapi-codegen
 *
 * @version v1
 */
export type CartItem = {
  userId: string;
  /**
   * @format int32
   */
  quantity: number;
  productDetail: ProductDetail;
};

export type ProductDetail = {
  id: string;
  name: string;
  description: string;
  category: ProductCategory;
  /**
   * @format int32
   */
  quantity: number;
  /**
   * @format decimal
   */
  price: number;
  imageUrl: string;
};

export type ProductCategory =
  | "Accessories"
  | "Hardware"
  | "Software"
  | "Books"
  | "Movies"
  | "Music"
  | "Games"
  | "Clothes"
  | "Other";
